In [18]:

import plotly
import pandas as pd
import numpy as np
# print out all numpy array
np.set_printoptions(threshold=np.inf)

from itertools import product

from sklearn import datasets
from sklearn.gaussian_process import GaussianProcessRegressor

In [19]:
# load the dataset
data = pd.read_excel('240905 Simulated Automated Screening Yields for DOE Practice.xlsx')
header = data.columns
data

Phase  Temperature (°C)  Rotation (RPM)  Current (mA)  Sim. Yields
0       1         20.000000      150.000000     20.000000           80
1       2         60.000000      150.000000     20.000000           90
2       3         20.000000      600.000000     20.000000           83
3       4         60.000000      600.000000     20.000000           93
4       5         20.000000      150.000000    100.000000           20
5       6         60.000000      150.000000    100.000000           30
6       7         20.000000      600.000000    100.000000           23
7       8         60.000000      600.000000    100.000000           33
8       9         40.000000      375.000000     60.000000           56
9      10          6.364143      375.000000     60.000000           41
10     11         40.000000      753.403387     60.000000           59
11     12         40.000000       -3.403387     60.000000           50
12     13         40.000000      375.000000    127.271713           11
13     14         73.635857      375.000000     60.000000           65

In [20]:
data  = data.to_numpy()
data = data[:,1:]
data

array([[ 20.        , 150.        ,  20.        ,  80.        ],
       [ 60.        , 150.        ,  20.        ,  90.        ],
       [ 20.        , 600.        ,  20.        ,  83.        ],
       [ 60.        , 600.        ,  20.        ,  93.        ],
       [ 20.        , 150.        , 100.        ,  20.        ],
       [ 60.        , 150.        , 100.        ,  30.        ],
       [ 20.        , 600.        , 100.        ,  23.        ],
       [ 60.        , 600.        , 100.        ,  33.        ],
       [ 40.        , 375.        ,  60.        ,  56.        ],
       [  6.36414339, 375.        ,  60.        ,  41.        ],
       [ 40.        , 753.40338686,  60.        ,  59.        ],
       [ 40.        ,  -3.40338686,  60.        ,  50.        ],
       [ 40.        , 375.        , 127.27171322,  11.        ],
       [ 73.63585661, 375.        ,  60.        ,  65.        ]])

In [21]:
# find the max value of the 'Sim. Yields' column
max_yield = np.argmax(data[:, 3])
max_yield

np.int64(3)

In [22]:
data[max_yield, :]

array([ 60., 600.,  20.,  93.])

In [23]:
regressor = GaussianProcessRegressor(random_state=0, kernel=None)

In [24]:
regressor.fit(data[:, 0:3], data[:, 3])

GaussianProcessRegressor(random_state=0)

In [25]:
print(f"score: {regressor.score(data[:, 0:3], data[:, 3])}")

score: 1.0


In [26]:
def bounds(data) -> list:
    mins = np.min(data, axis=0)
    maxs = np.max(data, axis=0)
    return [[mins_, maxs_] for mins_, maxs_ in zip(mins, maxs)]

In [27]:
# create the line space
def fullfact(bound_array, num_levels: int) -> np.ndarray:
    return np.array(list(product(*[np.linspace(min_, max_, num_levels) for min_, max_ in bound_array])))

In [28]:
result = fullfact(bounds(data[:, 0:3]), 20)

In [29]:
result

array([[  6.36414339,  -3.40338686,  20.        ],
       [  6.36414339,  -3.40338686,  25.64587964],
       [  6.36414339,  -3.40338686,  31.29175929],
       [  6.36414339,  -3.40338686,  36.93763893],
       [  6.36414339,  -3.40338686,  42.58351857],
       [  6.36414339,  -3.40338686,  48.22939822],
       [  6.36414339,  -3.40338686,  53.87527786],
       [  6.36414339,  -3.40338686,  59.5211575 ],
       [  6.36414339,  -3.40338686,  65.16703715],
       [  6.36414339,  -3.40338686,  70.81291679],
       [  6.36414339,  -3.40338686,  76.45879643],
       [  6.36414339,  -3.40338686,  82.10467607],
       [  6.36414339,  -3.40338686,  87.75055572],
       [  6.36414339,  -3.40338686,  93.39643536],
       [  6.36414339,  -3.40338686,  99.042315  ],
       [  6.36414339,  -3.40338686, 104.68819465],
       [  6.36414339,  -3.40338686, 110.33407429],
       [  6.36414339,  -3.40338686, 115.97995393],
       [  6.36414339,  -3.40338686, 121.62583358],
       [  6.36414339,  -3.40338

In [30]:
import plotly.graph_objects as go
import chart_studio.plotly as py

In [33]:
# plot the original data
fig = go.Figure(data=[go.Scatter3d(x=data[:, 0], y=data[:, 1], z=data[:, 2], mode='markers', marker=dict(size=4))])
py.iplot(fig)

PlotlyRequestError: Authentication credentials were not provided.